export const DRIVERS_TYPES = {
    "FETCH_DRIVERS_START" : 'drivers/FETCH_DRIVERS_START',
    "FETCH_DRIVERS_SUCCESS" : 'drivers/FETCH_DRIVERS_SUCCESS',
    "FETCH_DRIVERS_FAILURE" : 'drivers/FETCH_DRIVERS_FAILURE'
};