export const SHOP_PRODUCTS_TYPES = {
	FETCH_SHOP_PRODUCTS_START: 'shopProducts/FETCH_SHOP_PRODUCTS_START',
	FETCH_SHOP_PRODUCTS_SUCCESS: 'shopProducts/FETCH_SHOP_PRODUCTS_SUCCESS',
	FETCH_SHOP_PRODUCTS_FAILURE: 'shopProducts/FETCH_SHOP_PRODUCTS_FAILURE',
	SHOP_PRODUCTS_CHANGE_PAGENO: 'shopProducts/SHOP_PRODUCTS_CHANGE_PAGENO'
};
