export const AUTH_TYPES = {
    "AUTH_SET_ACCESS_TOKEN" : "auth/AUTH_SET_ACCESS_TOKEN",
    "AUTH_REFRESH_TOKEN" : 'auth/"AUTH_REFRESH_TOKEN"',
    "AUTH_LOGOUT" : "auth/AUTH_LOGOUT",
    "AUTH/GET_USER_INFO" : "auth/GET_USER_INFO",
    "PROFILE/UPDATE_PROFILE_PICTURE" : 'profile/UPDATE_PROFILE_PICTURE',
    "PROFILE/UPDATE_PROFILE_INFO" : 'profile/UPDATE_PROFILE_INFO',
}