export const SHOP_TEAMS_TYPES = {
	FETCH_SHOP_TEAMS_START: 'shopTeams/FETCH_SHOP_TEAMS_START',
	FETCH_SHOP_TEAMS_SUCCESS: 'shopTeams/FETCH_SHOP_TEAMS_SUCCESS',
	FETCH_SHOP_TEAMS_FAILURE: 'shopTeams/FETCH_SHOP_TEAMS_FAILURE'
};
