export const TEAMS_TYPES = {
    'FETCH_TEAMS_START' : 'teams/FETCH_TEAMS_START',
    'FETCH_TEAMS_CONSTRUCTOR_SUCCESSS' : 'teams/FETCH_TEAMS_CONSTRUCTOR_SUCCESSS',
    'FETCH_TEAMS_DRIVERS_SUCCESSS' : 'teams/FETCH_TEAMS_DRIVERS_SUCCESSS',
    'FETCH_TEAMS_FAILURE' : 'teams/FETCH_TEAMS_FAILURE',
}