export const LAST_RACE_RESULT_TYPES = {
    "FETCH_LAST_RACE_RESULT_START" : 'lastRaceResults/FETCH_DRIVERS_START',
    "FETCH_LAST_RACE_RESULT_SUCCESS" : 'lastRaceResults/FETCH_DRIVERS_SUCCESS',
    "FETCH_LAST_RACE_RESULT_FAILURE" : 'lastRaceResults/FETCH_DRIVERS_FAILURE'
}