export const SCHEDULE_TYPES = {
	FETCH_SCHEDULE_START: 'schedule/FETCH_DRIVERS_START',
	FETCH_SCHEDULE_SUCCESS: 'schedule/FETCH_DRIVERS_SUCCESS',
	FETCH_SCHEDULE_FAILURE: 'schedule/FETCH_DRIVERS_FAILURE',
	SET_UPCOMING_RACE: 'schedule/SET_UPCOMING_RACE'
};
