export const QUALYFING_TYPES = {
	QUALYFING_FETCH_START: 'qualyfing/QUALYFING_FETCH_START',
	QUALYFING_FETCH_SUCCESS: 'qualyfing/QUALYFING_FETCH_SUCCESS',
	QUALYFING_FETCH_FAILURE: 'qualyfing/QUALYFING_FETCH_FAILURE'
};
