export const STORE__USER_PRODUCTS_TYPES = {
	FETCH_SHOP_CART_START: 'store__userProducts/FETCH_SHOP_CART_START',
	FETCH_SHOP_FAVORITES_START: 'store__userProducts/FETCH_SHOP_FAVORITES_START',

	FETCH_SHOP_CART_SUCCESS: 'store__userProducts/FETCH_SHOP_CART_SUCCESS',
	FETCH_SHOP_FAVORITES_SUCESS: 'store__userProducts/FETCH_SHOP_FAVORITES_SUCESS',

	FETCH_SHOP_CART_FAILURE: 'store__userProducts/FETCH_SHOP_CART_FAILURE',
	FETCH_SHOP_FAVORITES_FAILURE: 'store__userProducts/FETCH_SHOP_FAVORITES_FAILURE',

	SHOP_CART_ADD: 'store__userProducts/SHOP_CART_ADD',
	SHOP_FAVORITES_ADD: 'store__userProducts/SHOP_FAVORITES_ADD',

	SHOP_CART_ADD_FAILURE: 'store__userProducts/SHOP_CART_ADD_FAILURE',
	SHOP_FAVORITES_ADD_FAILURE: 'store__userProducts/SHOP_FAVORITES_ADD_FAILURE'
};
