export const RACE_RESULTS_TYPES = {
    "FETCH_RACE_RESULTS_START" : "raceResults/FETCH_RACE_RESULTS_START",
    "FETCH_RACE_RESULTS_SUCCESS" : "raceResults/FETCH_RACE_RESULTS_SUCCESS",
    "FETCH_RACE_RESULTS_FAILURE" : "raceResults/FETCH_RACE_RESULTS_FAILURE"
};