export const SCHEDULE_DETAILS_TYPES = {
    'FETCH_SCHEDULE_DETAILS_START' : 'scheduleDetails/FETCH_SCHEDULE_DETAILS_START',
    'FETCH_SCHEDULE_DETAILS_SUCCESS' : 'scheduleDetails/FETCH_SCHEDULE_DETAILS_SUCCESS',
    'FETCH_SCHEDULE_DETAILS_FAILURE' : 'scheduleDetails/FETCH_SCHEDULE_DETAILS_FAILURE',
}